### PR TITLE
fix bad yaml

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This now passes ci

**Comment by SimonBiggs** [comment]
@CJ-Wright thank you for your help. I have a few data files that are used for the tests. They are decent in size and I don't want every user to have to download them. So I need to make it so that those files aren't included but get downloaded if they are needed.

That's what was causing that error. I would really like to be able to run pytest within the conda workflow, so I'll fix up that data file download issue.

**Comment by CJ-Wright** [comment]
That's fine. The issue in the meta.yaml was causing problems with the auto update bot so this PR was to get that working again.

**Comment by SimonBiggs** [comment]
Ahh sorry about that. I did wonder how pymedphys all of sudden got so much attention overnight.

**Comment by CJ-Wright** [comment]
Don't worry about it

**Pull request merged**
